language: java
jdk:
  - oraclejdk8
script:
  - gradle test
before_install:
  - sudo apt-get install sshpass -y
after_success:
    - pwd
    - echo `pwd`
    - tar -czf package.tgz build
    - tar -tvf package.tgz
    - export SSHPASS=$DEPLOY_PASS
    - echo $DEPLOY_PASS
    - sshpass -e scp package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh